### ISSUE TITLE
ARM support 

### ISSUE THREAD

**Issue by TomGlass** [ArchiveTeam/warrior-dockerfile#56]
Currently the ArchiveTeam Warrior does not support ARM devices.

We're investigating this and looking into building a new image, obviously this requires a lot of work as wget-at (formerly wget-lua) is a complicated setup. We need to validate it and ensure it produces valid content across multiple devices including but not limited to the various Raspberry Pis, Apple M1 architecture and other ARM SBCs such as Orange Pis.

For now we ask anyone working on it please do NOT test anything on live production projects, the risk of garbage data is not one we wish to take. We will begin testing hopefully next week. 

For now the current devices we have access to test with are sufficient but may require more later on

**Comment by billsargent** [comment]
I recommend removing the raspberry pi dockerfiles as well as modifying the README until Arm support is ready.

**Comment by TomGlass** [comment]
> I recommend removing the raspberry pi dockerfiles as well as modifying the README until Arm support is ready.

As it does still work for URLTeam to my knowledge I'll leave it but update readme

**Comment by Mechazawa** [comment]
What hurdles are there to get it running on ARM64?

**Comment by jhollowe** [comment]
The main thing is compiling dependencies for arm64, mainly wget-lua and any python packages that do not have wheels built for arm64 (zstandard). Once all software is compiled for arm64, the main functionality of the warrior should be the same as any other platform.

**Comment by billsargent** [comment]
Can it not be forced to compile things needed to arm32 then until a fix is in place? Can we even pass gcc flags to it?

**Comment by TomGlass** [comment]
> The main thing is compiling dependencies for arm64, mainly wget-lua and any python packages that do not have wheels built for arm64 (zstandard). Once all software is compiled for arm64, the main functionality of the warrior should be the same as any other platform.

It's sadly not that simple. We need to validate wget-at is stable and provides comparable data to amd64. We already are running 2 builds of wget-at due to an issue regarding the reddit project. I have just today finally got an RPI-4 up and I will begin testing next week.



> Can it not be forced to compile things needed to arm32 then until a fix is in place? Can we even pass gcc flags to it?

Sadly not.



> What hurdles are there to get it running on ARM64?

Highlighted just above.

**Comment by Veehxia** [comment]
Any news on this ?

**Comment by HeroCC** [comment]
Just wanted to give my 2 cents here -- it would be incredibly helpful to have a merged manifest with all of the architectures under one tag. This is possible with github actions, but I'm not sure how to do it with Drone's docker plugin. I run a kubernetes cluster with a mix of arm7, arm64, and amd64 boxes, and it would be much better to have one tag, where each box could pull from.

If there's anything you'd like the community to help with please let us know, I'd be happy to help get this up and running :)

**Comment by dieser-niko** [comment]
Any updates yet? Would be really nice if this would work before YouTube completely removes dislikes

**Comment by billsargent** [comment]
Is this being worked on? Currently the Dockerfile is completely outdated for raspberry pi OS. the "python" is no longer available for 2.7. Its needs to be python2 and python-wheel is for Python3 now. python-pip is no longer available for 2.7 as well. That would need to be manually installed during the image creation. 

I've been trying to work past this but now when I run the docker container, I get this

`Traceback (most recent call last):
  File "/usr/local/bin/run-warrior3", line 4, in <module>
    from seesaw.script.run_warrior import main
  File "/usr/local/lib/python3.10/dist-packages/seesaw/script/run_warrior.py", line 13, in <module>
    from seesaw.warrior import Warrior
  File "/usr/local/lib/python3.10/dist-packages/seesaw/warrior.py", line 20, in <module>
    from tornado.httpclient import AsyncHTTPClient
  File "/usr/local/lib/python3.10/dist-packages/tornado/httpclient.py", line 49, in <module>
    from tornado import httputil, stack_context
  File "/usr/local/lib/python3.10/dist-packages/tornado/httputil.py", line 106, in <module>
    class HTTPHeaders(collections.MutableMapping):
AttributeError: module 'collections' has no attribute 'MutableMapping'`

And I have no idea how to fix that.

**Comment by billsargent** [comment]
Here is my messy version of a Dockerfile that does work.  Feel free to clean it up. I know nothing about Docker.


`# Dockerfile for Raspberry Pi 2 and 3
FROM arm32v7/debian:bullseye-slim
LABEL version="1.0.0" \
	description="ArchiveTeam Warrior container for Raspberry Pi arm32"

# Install dependencies
RUN apt-get update
RUN apt-get install -y --no-install-recommends \
	curl \
	git \
	net-tools \
	libgnutls30 \
	liblua5.1-0 \
	python2.7 \
#	python-pip \
#	python-setuptools \
#	python-wheel \
	python3.9 \
	python3.9-dev \
#	python3-setuptools \
#	python3-wheel \
	sudo \
	wget \
	rsync \
	&& useradd -d /home/warrior -m -U warrior \
	&& echo "warrior ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers \
	&& mkdir -p /data/data \
	&& chown -R warrior:warrior /data/data

RUN apt-get install -y --no-install-recommends \
	autoconf automake  \
	build-essential \
	flex \
	libgnutls28-dev \
	libidn2-0-dev \
	uuid-dev \
	libpsl-dev \
	libpcre2-dev \
	liblua5.1-0-dev \
	libzstd-dev \
	zstd \
	zlib1g-dev \
	ca-certificates \
	python3-distutils
RUN curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
RUN python3.9 get-pip.py
RUN python3.9 -m pip install setuptools
RUN curl https://bootstrap.pypa.io/pip/2.7/get-pip.py --output get-pip2.py
RUN python2.7 get-pip2.py
RUN python2.7 -m pip install setuptools
RUN python3.9 -m pip install zstandard 

WORKDIR /tmp
#RUN curl -o wget-1.14.lua.LATEST.tar.bz2 \
#		https://warriorhq.archiveteam.org/downloads/wget-lua/wget-1.14.lua.LATEST.tar.bz2 \
#	&& tar -jxf /tmp/wget-1.14.lua.LATEST.tar.bz2 \
#		--strip-components=1

# https://github.com/ArchiveTeam/wget-lua/archive/refs/tags/v1.20.3-at.20211001.01.tar.gz
#RUN  git clone https://git.savannah.gnu.org/git/gnulib.git \

RUN apt-get install pkg-config automake autoconf2.69 texinfo autopoint liblua5.1-0 liblua5.1-0-dev  \
	lua-socket lua-socket-dev gettext texi2html gperf --reinstall -y \
	&& git clone --branch v1.20.3-at https://github.com/ArchiveTeam/wget-lua.git \
        && cd wget-lua && ./bootstrap && ./configure --with-ssl=gnutls --disable-nls \
	&& make \
	&& make install \
	&& cp src/wget /usr/bin/wget-lua \
	&& chmod a+x /usr/bin/wget-lua \
        && mkdir -p /home/warrior/data \
	&& cp /usr/bin/wget-lua /wget \
	&& cp /usr/bin/wget-lua /home/warrior/data/wget-at-gnutls \
	&& cp /usr/bin/wget-lua /wget-at \
	&& cp /usr/bin/wget-lua /home/warrior/data/wget-at


#RUN apt-get remove -y --purge \
#	autoconf \
#	curl \
#	build-essential \
#	flex \
#	libgnutls28-dev \
#	libidn2-0-dev \
#	uuid-dev \
#	libpsl-dev \
#	libpcre2-dev \
#	liblua5.1-0-dev \
#	zlib1g-dev \
#	&& apt-get clean -y \
#	&& apt-get autoremove -y --purge \
#	&& rm -r /var/lib/apt/lists/* \
#	&& rm -r /tmp/*

RUN python2.7 -m pip  install requests \
	&& python2.7 -m pip install six \
	&& python2.7 -m pip install warc \
	&& python3.9 -m pip install requests \
	&& python3.9 -m pip install six \
	&& python3.9 -m pip install warc

RUN python3.9 -m pip install seesaw

WORKDIR /home/warrior
USER warrior
RUN mkdir /home/warrior/projects

# Expose the persistent data to the host.  This will allow the user
# to not have to reconfigure the container across runs.
VOLUME /data/data
VOLUME /home/warrior/projects/config.json

# Expose web interface port
EXPOSE 8001

ENTRYPOINT ["run-warrior3", \
	"--projects-dir", "/home/warrior/projects", \
	"--data-dir", "/data/data", \
	"--warrior-hq", "http://warriorhq.archiveteam.org", \
	"--port", "8001", \
	"--real-shutdown"]`

**Comment by dieser-niko** [comment]
> I have created a Dockerfile for this that works. The only proejct that doesnt work is the ua one.
> 
> https://pastebin.com/1gpvEZ7E
> 
> I upgraded debian to bullseye. It needed a lot more packages. It needed a specific branch of wget-at
> 
> I commented out all cleanup. Someone with more experience can decide what works and doesnt. BUt this will get you going on Raspberry pi.

Doesn't seem to work. Could you provide instructions?

**Comment by billsargent** [comment]
> > I have created a Dockerfile for this that works. The only proejct that doesnt work is the ua one.
> > https://pastebin.com/1gpvEZ7E
> > I upgraded debian to bullseye. It needed a lot more packages. It needed a specific branch of wget-at
> > I commented out all cleanup. Someone with more experience can decide what works and doesnt. BUt this will get you going on Raspberry pi.
> 
> Doesn't seem to work. Could you provide instructions?

Can you tell me what doesn't work? I've built this on a Cubietruck board, and 3 RPi. Even a raspberry pi model 1. If you use a current raspiian OS lite, it should work straight out of the box following the same instructions from this repo. You can also use mine.  https://github.com/billsargent/at-warrior-rpi.git

**Comment by billsargent** [comment]
The last line of your log shows the problem. The data location is not writable. Change its permissions to allow it to be written. 

You can if you want, but I am not actively working on this project. I simply put it up for my own needs. It has built and ran on even non-raspberry pi devices for me. I'm currently running it on a cubietruck SOC with armbian.

**Comment by JustAnotherArchivist** [comment]
I didn't see these comments at the time, but @billsargent @dieser-niko it's fine if you want to experiment with ARM support, but **don't run it against the official tracker**. wget-at has not been verified to work correctly on ARM, and so you might be polluting our work with bad data. So please set up your own tracker instance and projects for testing purposes.

**Comment by JustAnotherArchivist** [comment]
More accurately: very few people know how to properly verify wget-at, and they (myself included) lack the time to work on maintenance tasks such as this (as opposed to working on urgent archival projects or fixing stuff that breaks). As you mention, it's not a small task to get this right.

**Comment by billsargent** [comment]
It would be great to get it going though because many people have tons of low power arm devices that could contribute. But it's a big hassle right now. Maybe some day though :) 

I have a fork of this and I'm gonna pull the plug on it. I dont want others corrupting things with what I did as an experiment.

**Comment by JustAnotherArchivist** [comment]
Oh yeah, it would absolutely be great to have it! There are also some interesting providers with very powerful ARM-based servers, e.g. Hetzner's RX line.

**Comment by berezovskyi** [comment]
Just a side note: I can contribute a warrior instance by spinning up a container on an x86 cloud VM, but if AT wants a warrior on a residential IP address, I can only spare a Raspberry Pi for that. Hope this adds a bit of motivation to this issue apart from requesting more architectures for fun.

**Comment by mikeakers** [comment]
Adding another vote for this issue, I have an ARM64 NAS server in my hope that I would love to be able to use to contribute to this project.

**Comment by penyuan** [comment]
I'm not much of a developer (sorry!), but am happy to help test this should ARM support be eventually developed.

ArchiveTeam is such a great cause, IMHO it'll be a huge win to bring onboard the enormous compute power all the ARM devices that are out there! Therefore ARM support is probably worth the strategic effort!

**Comment by JustAnotherArchivist** [comment]
Please don't insinuate that we don't care. We do. As I explained above, we just don't have the time to properly audit this currently. Remember we all do this voluntarily in our free time, and stuff's being put on fire constantly (cf. Imgur, Reddit), which usually keeps us more than busy already. That said, there is a rough internal plan for how this might be able to move forward. It depends on several other steps that need to happen first though. I wouldn't recommend holding your breath, but we do want to fix this eventually. And, like you, we'd like to get it done ASAP, but it unfortunately isn't at the top of our urgency list due to the above.

**Comment by billsargent** [comment]
> Please don't insinuate that we don't care. We do. As I explained above, we just don't have the time to properly audit this currently. Remember we all do this voluntarily in our free time, and stuff's being put on fire constantly (cf. Imgur, Reddit), which usually keeps us more than busy already. That said, there is a rough internal plan for how this might be able to move forward. It depends on several other steps that need to happen first though. I wouldn't recommend holding your breath, but we do want to fix this eventually. And, like you, we'd like to get it done ASAP, but it unfortunately isn't at the top of our urgency list due to the above.

I worded that wrong. It wasn't a dig at you or the devs. I meant people in general that actually know more than I do about it. If people want this to work, more people with experience AND TIME need to join. But that doesn't appear to be happening. And that is what I meant by not caring. Because to be honest, there should be a huge number of people with extensive experience offering their help. And there isn't. So I apologize for making it sound like this was a dig at the people currently working. I know you're busy and I know this is volunteer work but I actually would expect wit ha feature like this that there'd be a lot more volunteers willing to dig into it and supply patches and fixes.

**Comment by JustAnotherArchivist** [comment]
I guess this was never properly explained, so let me give you some perspective on that.

I would expect the core of wget to be fine on ARM, though I haven't checked whether they actually test it; there's a reasonable test suite though, so that's easy enough to run and double-check. The potentially problematic parts are WARC writing (poorly tested upstream, if at all) and our customisations. There are few people on this planet who know the WARC specification well enough to validate it, and even fewer familiar with the specification for zstd-compressed WARCs. You can probably count the latter on one hand. To my knowledge, we (AT) are still the only ones using that. So there are two or three people from AT, someone at IA, and two people who worked on the spec who could theoretically verify the WARC stuff; practically, it has to be one of the 2-3 from AT. For the customisations, it's only those 2-3 anyway, or maybe even less (I'm familiar with WARCs but not overly with the custom stuff in wget-at, for example). Add to this the various undocumented intentional quirks of our code.

So yeah, there are literally only a couple people in the world with the necessary knowledge and experience to do this. That's why it's bottlenecked so hard.

**Comment by Meow-purr** [comment]
+1

**Comment by Meow-purr** [comment]
or quemo

**Comment by Meow-purr** [comment]
ive got the hardware

**Comment by billsargent** [comment]
> ive got the hardware

Are you incapable of writing your thoughts in one reply?

**Comment by Meow-purr** [comment]
i fougtth the comments immedeatly after i posted the first

**Comment by JustAnotherArchivist** [comment]
No, that's why the issue isn't closed.

**Comment by sufehmi** [comment]
Subscribed with hope to be notified when I can run this on my raspi machines, thanks.

**Comment by JamieMagee** [comment]
I took a pass at this. The main blocker was wget-lua's Dockerfile hardcoding `x86_64-linux-gnu` paths for the NSS libraries. Swapped those out for `dpkg-architecture -qDEB_HOST_MULTIARCH` so it picks up the right paths on arm64 (or whatever else). Also added `linux/arm64` to the Drone CI platforms across all three repos in the build chain.

PRs:
- https://github.com/ArchiveTeam/wget-lua/pull/29
- https://github.com/ArchiveTeam/grab-base-df/pull/8
- https://github.com/ArchiveTeam/warrior-dockerfile/pull/99

**Comment by billsargent** [comment]
I'm glad to see someone worked on this. With so many arm devices sitting around, this would be perfect for idle devices.
