### ISSUE TITLE
Error when running reddit project `Exception: No usable Wget+At found`

### ISSUE THREAD

**Issue by pirate** [ArchiveTeam/warrior-dockerfile#58]
I'm having trouble running the `reddit` project on my warrior. I'm using the latest image available on Docker Hub (`7d111a6ae19a`) on an `Ubuntu 20.04 amd64` host machine with the latest version of Docker (`20.10.6`).

Selecting reddit from the UI or from the environment variables doesn't work, the UI button doesn't respond and the "Current Project" page remains empty.

Here's my `docker-compose.yml` config:
```yaml
version: '3.9'

services:
  archivewarrior:
    image: archiveteam/warrior-dockerfile
    ports:
      - 8001:8001
    environment:
      - SELECTED_PROJECT=auto
      - CONCURRENT_ITEMS=6
      - DOWNLOADER=redacted
      - WARRIOR_ID=redacted
      - HTTP_USERNAME=redacted
      - HTTP_PASSWORD=redacted
```
```bash
$ docker-compose images
              Container                            Repository              Tag       Image Id       Size
----------------------------------------------------------------------------------------------------------
zervicearchivewarrior_archivewarrior_1   archiveteam/warrior-dockerfile   latest   7d111a6ae19a   235.1 MB

$ docker-compose up
```

Leads to this:
```logs
Seesaw version: 0.10.3
Python version: 3.9.4 (default, Apr 5 2021, 18:26:27) [GCC 8.3.0]

2021-06-01 00:20:43,540 - seesaw.warrior - DEBUG - Update warrior hq.
2021-06-01 00:20:43,540 - seesaw.warrior - DEBUG - Warrior ID 'theSquashSH'.
2021-06-01 00:20:43,964 - seesaw.warrior - DEBUG - Select project reddit
2021-06-01 00:20:43,964 - seesaw.warrior - DEBUG - Start selected project reddit (reinstall=False)
2021-06-01 00:20:43,964 - seesaw.warrior - DEBUG - Install project reddit
2021-06-01 00:20:43,964 - seesaw.warrior - DEBUG - git clone
2021-06-01 00:20:44,564 - seesaw.warrior - DEBUG - git operation: Cloning into '/home/warrior/projects/reddit'...

2021-06-01 00:20:44,565 - seesaw.warrior - DEBUG - Install complete Cloning into '/home/warrior/projects/reddit'...

2021-06-01 00:20:44,566 - seesaw.warrior - DEBUG - Result of the install process: True
2021-06-01 00:20:44,566 - seesaw.warrior - DEBUG - Clone project reddit /home/warrior/projects/reddit
2021-06-01 00:20:44,569 - seesaw.warrior - DEBUG - Cloning version 4b976e2
2021-06-01 00:20:44,595 - seesaw.warrior - DEBUG - Load pipeline /home/warrior/data/projects/reddit-4b976e2/pipeline.py
2021-06-01 00:20:44,595 - seesaw.warrior - DEBUG - Pipeline has been read. Begin ConfigValue collection
2021-06-01 00:20:44,596 - seesaw.warrior - DEBUG - Executing pipeline
2021-06-01 00:20:44,713 - seesaw.warrior - ERROR - Error loading pipeline
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/seesaw/warrior.py", line 736, in start_selected_project
    (project, pipeline, config_values) = self.load_pipeline(
  File "/usr/local/lib/python3.9/site-packages/seesaw/warrior.py", line 686, in load_pipeline
    exec(pipeline_str, local_context, global_context)
  File "<string>", line 54, in <module>
Exception: No usable Wget+At found.
2021-06-01 00:20:44,714 - seesaw.warrior - WARNING - Project reddit did not install correctly and we're ignoring this problem.
2021-06-01 00:23:38,385 - seesaw.warrior - DEBUG - Select project reddit
```

Possibly related:
- https://github.com/ArchiveTeam/warrior-dockerfile/pull/44
- https://github.com/ArchiveTeam/warrior-dockerfile/issues/42
- https://github.com/ArchiveTeam/warrior-extras-installer/issues/2

Any ideas @SrihariThalla / @km09 / others? Thanks in advance!

**Comment by brovary3154** [comment]
I have this same issue where the Current Project page remains empty.

**Comment by TomGlass** [comment]
Hey we've fixed the docker-compose with the latest PR. Please try now, the dockerhub image is slightly obsolete

**Comment by pirate** [comment]
Is it possible to keep the the docker hub image up to date in the future? It's a bit of a drag to keep changing the repo / image location (just for context, this is the 3rd time I've been told to change it to something new)
