### ISSUE TITLE
No usable Wget+At found

### ISSUE THREAD

**Issue by elit3ge** [ArchiveTeam/warrior-dockerfile#60]
Ubuntu Docker
No scrolling terminals on the front page.
Got it to work on URLS.

```
2021-06-13 13:23:58,614 - seesaw.warrior - DEBUG - Cloning version 91153b3,
2021-06-13 13:24:50,536 - seesaw.warrior - WARNING - Project reddit did not install correctly and we're ignoring this problem.,
Exception: No usable Wget+At found.,
  File "<string>", line 54, in <module>,
  File "/usr/local/lib/python3.9/site-packages/seesaw/warrior.py", line 686, in load_pipeline,
    (project, pipeline, config_values) = self.load_pipeline(,
    exec(pipeline_str, local_context, global_context),
  File "/usr/local/lib/python3.9/site-packages/seesaw/warrior.py", line 736, in start_selected_project,
Traceback (most recent call last):,
2021-06-13 13:24:50,536 - seesaw.warrior - ERROR - Error loading pipeline,
2021-06-13 13:24:50,457 - seesaw.warrior - DEBUG - Executing pipeline,
2021-06-13 13:24:50,456 - seesaw.warrior - DEBUG - Pipeline has been read. Begin ConfigValue collection,
2021-06-13 13:24:50,455 - seesaw.warrior - DEBUG - Load pipeline /home/warrior/data/projects/reddit-4b976e2/pipeline.py,
done.,
Cloning into '/home/warrior/data/projects/reddit-4b976e2'...,
2021-06-13 13:24:50,354 - seesaw.warrior - DEBUG - Cloning version 4b976e2,
2021-06-13 13:24:50,346 - seesaw.warrior - DEBUG - Clone project reddit /home/warrior/projects/reddit,
2021-06-13 13:24:50,346 - seesaw.warrior - DEBUG - Result of the install process: True,
2021-06-13 13:24:50,344 - seesaw.warrior - DEBUG - git operation: Cloning into '/home/warrior/projects/reddit'...,
2021-06-13 13:24:50,345 - seesaw.warrior - DEBUG - Install complete Cloning into '/home/warrior/projects/reddit'...,
2021-06-13 13:24:49,450 - seesaw.warrior - DEBUG - git clone,
2021-06-13 13:24:49,449 - seesaw.warrior - DEBUG - Install project reddit,
  File "<string>", line 47, in <module>,
2021-06-13 13:23:58,689 - seesaw.warrior - WARNING - Project webs did not install correctly and we're ignoring this problem.,
2021-06-13 13:24:36,421 - seesaw.warrior - DEBUG - Select project webs,
2021-06-13 13:24:49,448 - seesaw.warrior - DEBUG - Select project reddit,
2021-06-13 13:24:49,449 - seesaw.warrior - DEBUG - Start selected project reddit (reinstall=False),
Cloning into '/home/warrior/data/projects/webs-91153b3'...,
2021-06-13 13:23:58,661 - seesaw.warrior - DEBUG - Load pipeline /home/warrior/data/projects/webs-91153b3/pipeline.py,
2021-06-13 13:23:58,663 - seesaw.warrior - DEBUG - Pipeline has been read. Begin ConfigValue collection,
2021-06-13 13:23:58,607 - seesaw.warrior - DEBUG - Clone project webs /home/warrior/projects/webs,
2021-06-13 13:23:58,606 - seesaw.warrior - DEBUG - Result of the install process: True,
2021-06-13 13:23:58,605 - seesaw.warrior - DEBUG - Install complete Cloning into '/home/warrior/projects/webs'...,
2021-06-13 13:23:58,604 - seesaw.warrior - DEBUG - git operation: Cloning into '/home/warrior/projects/webs'...,
2021-06-13 13:23:58,663 - seesaw.warrior - DEBUG - Executing pipeline,
2021-06-13 13:23:58,687 - seesaw.warrior - ERROR - Error loading pipeline
```

**Comment by km09** [comment]
Closing as this'll be a project-specific issue. If still present, please raise against the project.
