### ISSUE TITLE
Warrior breaks on Reddit

### ISSUE THREAD

**Issue by RiversideRocks** [ArchiveTeam/warrior-dockerfile#62]
I'm trying to work on Reddit, but I keep getting errors:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/seesaw/warrior.py", line 736, in start_selected_project
    (project, pipeline, config_values) = self.load_pipeline(
  File "/usr/local/lib/python3.9/site-packages/seesaw/warrior.py", line 686, in load_pipeline
    exec(pipeline_str, local_context, global_context)
  File "<string>", line 54, in <module>
Exception: No usable Wget+At found.
2021-10-01 22:10:27,752 - seesaw.warrior - WARNING - Project reddit did not install correctly and we're ignoring this problem.
```

Any idea what the problem is? I've restarted by warrior.

**Comment by ManBehindPlan** [comment]
I get the same error, looks like the WGET is the wrong version:

`2021-10-07 04:22:12,916 - seesaw.warrior - DEBUG - Load pipeline /home/warrior/data/projects/reddit-8a3f8cd/pipeline.py
2021-10-07 04:22:12,919 - seesaw.warrior - DEBUG - Pipeline has been read. Begin ConfigValue collection
2021-10-07 04:22:12,921 - seesaw.warrior - DEBUG - Executing pipeline
Looking for Wget+AT in ./wget-at
./wget-at: [Errno 2] No such file or directory: './wget-at'
Looking for Wget+AT in /home/warrior/data/wget-at-gnutls
/home/warrior/data/wget-at-gnutls: Incorrect Wget+AT version (want ['GNU Wget 1.20.3-at.20211001.01']).
2021-10-07 04:22:13,455 - seesaw.warrior - ERROR - Error loading pipeline
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/seesaw/warrior.py", line 736, in start_selected_project
    (project, pipeline, config_values) = self.load_pipeline(
  File "/usr/local/lib/python3.9/site-packages/seesaw/warrior.py", line 686, in load_pipeline
    exec(pipeline_str, local_context, global_context)
  File "<string>", line 54, in <module>
Exception: No usable Wget+At found.
2021-10-07 04:22:13,483 - seesaw.warrior - WARNING - Project reddit did not install correctly and we're ignoring this problem.
2021-10-07 04:31:46,271 - seesaw.warrior - DEBUG - Update warrior hq.
2021-10-07 04:31:46,272 - seesaw.warrior - DEBUG - Warrior ID ''.
2021-10-07 04:31:46,921 - seesaw.warrior - DEBUG - Select project reddit`

**Comment by PokeyTheCat** [comment]
I was having the same problem. Usually I'd force pull the latest image from docker-hub, but it turns out we should be using the `atdr.meo.ws` registry.

After adding `atdr.meo.ws` as a registry and pulling `atdr.meo.ws/archiveteam/warrior-dockerfile:latest` everything works and it has the latest `wget-at`.

**Comment by iFloris** [comment]
I too have this problem, but with other projects:
```
2022-06-15 14:08:29,761 - seesaw.warrior - ERROR - Error loading pipeline
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/seesaw/warrior.py", line 736, in start_selected_project
    (project, pipeline, config_values) = self.load_pipeline(
  File "/usr/local/lib/python3.9/site-packages/seesaw/warrior.py", line 686, in load_pipeline
    exec(pipeline_str, local_context, global_context)
  File "<string>", line 55, in <module>
Exception: No usable Wget+At found.
2022-06-15 14:08:29,772 - seesaw.warrior - WARNING - Project telegram did not install correctly and we're ignoring this problem.
```
My warriors are already using `atdr.meo.ws` as a registry, so it should have the latest `wget-at`, should it not?

**Comment by Arkiver2** [comment]
This is fixed now, we're using the latest Wget-AT.

**Comment by Scott-St** [comment]
Looks like this is happening again.

**Comment by Jshanks** [comment]
> Looks like this is happening again.

Same, using :latest


`2023-04-18 15:58:50,296 - seesaw.warrior - DEBUG - Start selected project reddit (reinstall=False)
2023-04-18 15:58:50,296 - seesaw.warrior - DEBUG - Check project has update reddit
2023-04-18 15:58:50,305 - seesaw.warrior - DEBUG - git fetch
2023-04-18 15:58:50,637 - seesaw.warrior - DEBUG - False
2023-04-18 15:58:50,639 - seesaw.warrior - DEBUG - Clone project reddit /home/warrior/projects/reddit
2023-04-18 15:58:50,645 - seesaw.warrior - DEBUG - Cloning version 7f4db17
2023-04-18 15:58:50,646 - seesaw.warrior - DEBUG - Load pipeline /home/warrior/data/projects/reddit-7f4db17/pipeline.py
2023-04-18 15:58:50,647 - seesaw.warrior - DEBUG - Pipeline has been read. Begin ConfigValue collection
2023-04-18 15:58:50,647 - seesaw.warrior - DEBUG - Executing pipeline
2023-04-18 15:58:50,666 - seesaw.warrior - ERROR - Error loading pipeline
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/seesaw/warrior.py", line 736, in start_selected_project
    (project, pipeline, config_values) = self.load_pipeline(
  File "/usr/local/lib/python3.9/site-packages/seesaw/warrior.py", line 686, in load_pipeline
    exec(pipeline_str, local_context, global_context)
  File "<string>", line 56, in <module>
Exception: No usable Wget+At found.
2023-04-18 15:58:50,668 - seesaw.warrior - WARNING - Project reddit did not install correctly and we're ignoring this problem.`
