### ISSUE TITLE
Exception: No usable Wget+At found.

### ISSUE THREAD

**Issue by Scott-St** [ArchiveTeam/warrior-dockerfile#70]
Latest docker container breaks wget again.

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/seesaw/warrior.py", line 736, in start_selected_project
    (project, pipeline, config_values) = self.load_pipeline(
  File "/usr/local/lib/python3.9/site-packages/seesaw/warrior.py", line 686, in load_pipeline
    exec(pipeline_str, local_context, global_context)
  File "<string>", line 56, in <module>
Exception: No usable Wget+At found.
```

**Comment by Jshanks** [comment]
Seeing the same behavior here.

`2023-04-18 15:58:50,296 - seesaw.warrior - DEBUG - Start selected project reddit (reinstall=False)`
`2023-04-18 15:58:50,296 - seesaw.warrior - DEBUG - Check project has update reddit`
`2023-04-18 15:58:50,305 - seesaw.warrior - DEBUG - git fetch`
`2023-04-18 15:58:50,637 - seesaw.warrior - DEBUG - False`
`2023-04-18 15:58:50,639 - seesaw.warrior - DEBUG - Clone project reddit /home/warrior/projects/reddit`
`2023-04-18 15:58:50,645 - seesaw.warrior - DEBUG - Cloning version 7f4db17`
`2023-04-18 15:58:50,646 - seesaw.warrior - DEBUG - Load pipeline /home/warrior/data/projects/reddit-7f4db17/pipeline.py`
`2023-04-18 15:58:50,647 - seesaw.warrior - DEBUG - Pipeline has been read. Begin ConfigValue collection`
`2023-04-18 15:58:50,647 - seesaw.warrior - DEBUG - Executing pipeline`
`2023-04-18 15:58:50,666 - seesaw.warrior - ERROR - Error loading pipeline`
`Traceback (most recent call last):`
 ` File "/usr/local/lib/python3.9/site-packages/seesaw/warrior.py", line 736, in start_selected_project`
  `  (project, pipeline, config_values) = self.load_pipeline(`
  `File "/usr/local/lib/python3.9/site-packages/seesaw/warrior.py", line 686, in load_pipeline`
   ` exec(pipeline_str, local_context, global_context)`
  `File "<string>", line 56, in <module>`
`Exception: No usable Wget+At found.`
`2023-04-18 15:58:50,668 - seesaw.warrior - WARNING - Project reddit did not install correctly and we're ignoring this problem.`

**Comment by 0xEmma** [comment]
Also having this issue

**Comment by trentwiles** [comment]
Same issue with the imgur project.

**Comment by tech234a** [comment]
The Reddit and Imgur projects should be working on the Warrior now.

**Comment by lanarchy** [comment]
Having same issue myself

**Comment by ziggo0** [comment]
Also happening to me as of today. Latest warrior image, both in VMware and VirtualBox.

**Comment by AJO-Python** [comment]
Happening to me for all projects.
I have watchtower keeping the warrior image on latest.

**Comment by AJO-Python** [comment]
@Arkiver2 thanks for the quick reply and explanation!
I have watchtower managing the warrior container so will just wait for the updates to roll through.

**Comment by Arkiver2** [comment]
Thank you @AJO-Python , if it is still not running in, say, 3 hours, please ping us here again! (We're in the process of moving all projects still to the new Wget-AT.)

**Comment by ziggo0** [comment]
@Arkiver2 it appears to be working for me now. All of my refreshed warriors are up and running. Thank you.

A work around I did find was to click the regular Reddit project, stop that, then back to ArchiveTeam’s Choice.

**Comment by Arkiver2** [comment]
@ziggo0 yeah, that will initialize project again, including pulling the newest version. So indeed a speed up.

**Comment by szymmirr** [comment]
Periscope
```
2023-12-09 04:24:47,923 - seesaw.warrior - DEBUG - Select project periscope
2023-12-09 04:24:47,931 - seesaw.warrior - DEBUG - Start selected project periscope (reinstall=False)
2023-12-09 04:24:47,933 - seesaw.warrior - DEBUG - Install project periscope
2023-12-09 04:24:47,948 - seesaw.warrior - DEBUG - git clone
2023-12-09 04:25:01,068 - seesaw.warrior - DEBUG - git operation: Cloning into '/home/warrior/projects/periscope'...

2023-12-09 04:25:01,069 - seesaw.warrior - DEBUG - Install complete Cloning into '/home/warrior/projects/periscope'...

2023-12-09 04:25:01,071 - seesaw.warrior - DEBUG - Result of the install process: True
2023-12-09 04:25:01,071 - seesaw.warrior - DEBUG - Clone project periscope /home/warrior/projects/periscope
2023-12-09 04:25:01,076 - seesaw.warrior - DEBUG - Cloning version f63acd1
2023-12-09 04:25:01,092 - seesaw.warrior - DEBUG - Load pipeline /home/warrior/data/projects/periscope-f63acd1/pipeline.py
2023-12-09 04:25:01,094 - seesaw.warrior - DEBUG - Pipeline has been read. Begin ConfigValue collection
2023-12-09 04:25:01,094 - seesaw.warrior - DEBUG - Executing pipeline
2023-12-09 04:25:01,328 - seesaw.warrior - ERROR - Error loading pipeline
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/seesaw/warrior.py", line 736, in start_selected_project
    (project, pipeline, config_values) = self.load_pipeline(
  File "/usr/local/lib/python3.9/site-packages/seesaw/warrior.py", line 686, in load_pipeline
    exec(pipeline_str, local_context, global_context)
  File "<string>", line 52, in <module>
Exception: No usable Wget+At found.
2023-12-09 04:25:01,332 - seesaw.warrior - WARNING - Project periscope did not install correctly and we're ignoring this problem.
```

VK
```
2023-12-09 04:26:30,879 - seesaw.warrior - DEBUG - Select project vkontakte
2023-12-09 04:26:30,881 - seesaw.warrior - DEBUG - Start selected project vkontakte (reinstall=False)
2023-12-09 04:26:30,881 - seesaw.warrior - DEBUG - Install project vkontakte
2023-12-09 04:26:30,882 - seesaw.warrior - DEBUG - git clone
2023-12-09 04:26:37,230 - seesaw.warrior - DEBUG - git operation: Cloning into '/home/warrior/projects/vkontakte'...

2023-12-09 04:26:37,232 - seesaw.warrior - DEBUG - Install complete Cloning into '/home/warrior/projects/vkontakte'...

2023-12-09 04:26:37,233 - seesaw.warrior - DEBUG - Result of the install process: True
2023-12-09 04:26:37,234 - seesaw.warrior - DEBUG - Clone project vkontakte /home/warrior/projects/vkontakte
2023-12-09 04:26:37,251 - seesaw.warrior - DEBUG - Cloning version 5a4111a
2023-12-09 04:26:37,274 - seesaw.warrior - DEBUG - Load pipeline /home/warrior/data/projects/vkontakte-5a4111a/pipeline.py
2023-12-09 04:26:37,275 - seesaw.warrior - DEBUG - Pipeline has been read. Begin ConfigValue collection
2023-12-09 04:26:37,275 - seesaw.warrior - DEBUG - Executing pipeline
2023-12-09 04:26:37,298 - seesaw.warrior - ERROR - Error loading pipeline
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/seesaw/warrior.py", line 736, in start_selected_project
    (project, pipeline, config_values) = self.load_pipeline(
  File "/usr/local/lib/python3.9/site-packages/seesaw/warrior.py", line 686, in load_pipeline
    exec(pipeline_str, local_context, global_context)
  File "<string>", line 54, in <module>
Exception: No usable Wget+At found.
2023-12-09 04:26:37,299 - seesaw.warrior - WARNING - Project vkontakte did not install correctly and we're ignoring this problem.
```

Stack Exchange
```
2023-12-09 04:29:15,732 - seesaw.warrior - DEBUG - Select project stack-exchange
2023-12-09 04:29:15,734 - seesaw.warrior - DEBUG - Start selected project stack-exchange (reinstall=False)
2023-12-09 04:29:15,735 - seesaw.warrior - DEBUG - Install project stack-exchange
2023-12-09 04:29:15,738 - seesaw.warrior - DEBUG - git clone
2023-12-09 04:29:19,171 - seesaw.warrior - DEBUG - git operation: Cloning into '/home/warrior/projects/stack-exchange'...
warning: You appear to have cloned an empty repository.

2023-12-09 04:29:19,173 - seesaw.warrior - DEBUG - Install complete Cloning into '/home/warrior/projects/stack-exchange'...
warning: You appear to have cloned an empty repository.

2023-12-09 04:29:19,174 - seesaw.warrior - DEBUG - Result of the install process: True
2023-12-09 04:29:19,176 - seesaw.warrior - DEBUG - Clone project stack-exchange /home/warrior/projects/stack-exchange
2023-12-09 04:29:19,182 - seesaw.warrior - DEBUG - Cloning version 
2023-12-09 04:29:19,197 - seesaw.warrior - DEBUG - Load pipeline /home/warrior/data/projects/stack-exchange-/pipeline.py
2023-12-09 04:29:19,198 - seesaw.warrior - ERROR - Error loading pipeline
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/seesaw/warrior.py", line 736, in start_selected_project
    (project, pipeline, config_values) = self.load_pipeline(
  File "/usr/local/lib/python3.9/site-packages/seesaw/warrior.py", line 674, in load_pipeline
    with open(pipeline_path) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/warrior/data/projects/stack-exchange-/pipeline.py'
2023-12-09 04:29:19,199 - seesaw.warrior - WARNING - Project stack-exchange did not install correctly and we're ignoring this problem.
```

**Comment by JustAnotherArchivist** [comment]
@szymmirr VK and Stack Exchange are marked as 'WIP' (work in progress, i.e. not ready yet), and Periscope is 'paused'. In other words, those three are not currently operational, and errors are to be expected.

**Comment by Ramblurr** [comment]
Getting this with the latest image `latest@sha256:1df66b037c4a8c915b380bde4ffd59ced214d809779a8c3cac07685a618ab7b5` for project telegram.

**Comment by flotwig** [comment]
This error still occurs with the latest warrior-dockerfile for telegram, imgur, mediafire, pastebin and imgur.
